# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Retinue < Formula
  desc "AI-powered parallel task orchestration for codebases"
  homepage "https://github.com/wolandomny/retinue"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wolandomny/retinue/releases/download/v0.1.0/retinue_darwin_amd64.tar.gz"
      sha256 "3c10fa28eec5eeaf826ae6d33620510e6fd58dcc1ad547b75d7d24e17fa5ff41"

      define_method(:install) do
        bin.install "retinue"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wolandomny/retinue/releases/download/v0.1.0/retinue_darwin_arm64.tar.gz"
      sha256 "f7416c27a306bd5efb8e6b1902a4c3229eacdf09f09fb6f8ff3e321273e0ef6f"

      define_method(:install) do
        bin.install "retinue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wolandomny/retinue/releases/download/v0.1.0/retinue_linux_amd64.tar.gz"
      sha256 "2041b19243f041395f70feea10bba315b4d43dd6f08bf8c0865df8d9fae73902"
      define_method(:install) do
        bin.install "retinue"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wolandomny/retinue/releases/download/v0.1.0/retinue_linux_arm64.tar.gz"
      sha256 "fc876b8255ce3f782990206c5fe0a4af157b632d4e83420c12d32b5312408b9c"
      define_method(:install) do
        bin.install "retinue"
      end
    end
  end

  test do
    system "#{bin}/retinue", "version"
  end
end
