# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Retinue < Formula
  desc "AI-powered parallel task orchestration for codebases"
  homepage "https://github.com/wolandomny/retinue"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wolandomny/retinue/releases/download/v0.2.0/retinue_darwin_amd64.tar.gz"
      sha256 "559e5e5c8c4ab572f36520e55b9be2e53541aa846ee35c2f00c36d0e13454c92"

      define_method(:install) do
        bin.install "retinue"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wolandomny/retinue/releases/download/v0.2.0/retinue_darwin_arm64.tar.gz"
      sha256 "d093e8dcb80405f421e2b3b44dd488758e2cc04b153b2e609e2306817878b9b2"

      define_method(:install) do
        bin.install "retinue"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wolandomny/retinue/releases/download/v0.2.0/retinue_linux_amd64.tar.gz"
      sha256 "6d0d3d4cd9ecfae1aea6312ff57f2a0da08416434f32951263db74642cb955bd"
      define_method(:install) do
        bin.install "retinue"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wolandomny/retinue/releases/download/v0.2.0/retinue_linux_arm64.tar.gz"
      sha256 "f1f1e819654aa7c84b9d09a15a9ccd8a9d5daedbf6524f0ac15c1b0b97df9290"
      define_method(:install) do
        bin.install "retinue"
      end
    end
  end

  test do
    system "#{bin}/retinue", "version"
  end
end
